# Generated by Django 5.2.8 on 2025-11-23 01:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('scenario', 'One-shot Scenario'), ('campaign', 'Full Campaign')], default='scenario', max_length=20)),
                ('target_length', models.CharField(choices=[('short', 'Short (5-10 turns)'), ('medium', 'Medium (20-50 turns)'), ('long', 'Long (100+ turns)'), ('custom', 'Custom')], default='medium', max_length=20)),
                ('failure_style', models.CharField(choices=[('fail_forward', 'Fail Forward'), ('strict_raw', 'Strict RAW')], default='fail_forward', max_length=20)),
                ('content_rating', models.CharField(choices=[('G', 'G - General'), ('PG', 'PG - Parental Guidance'), ('PG13', 'PG-13'), ('R', 'R - Restricted'), ('NC17', 'NC-17 - Adults Only')], default='PG13', max_length=10)),
                ('start_universe_time', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='CanonicalCampaignState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_index', models.PositiveIntegerField()),
                ('state_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canonical Campaign State',
                'verbose_name_plural': 'Canonical Campaign States',
                'ordering': ['campaign', '-turn_index'],
            },
        ),
        migrations.CreateModel(
            name='TurnEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_index', models.PositiveIntegerField()),
                ('user_input_text', models.TextField()),
                ('llm_response_text', models.TextField()),
                ('roll_spec_json', models.JSONField(default=dict)),
                ('roll_results_json', models.JSONField(default=dict)),
                ('state_patch_json', models.JSONField(default=dict)),
                ('canonical_state_hash', models.CharField(max_length=64)),
                ('lore_deltas_json', models.JSONField(default=list)),
                ('universe_time_after_turn', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Turn Event',
                'verbose_name_plural': 'Turn Events',
                'ordering': ['campaign', 'turn_index'],
            },
        ),
    ]
