# Generated by Django 5.2.8 on 2025-11-23 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('characters', '0001_initial'),
        ('universes', '0001_homebrew_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='character_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='characters.charactersheet'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='universes.universe'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canonicalcampaignstate',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_snapshots', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='turnevent',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='campaigns.campaign'),
        ),
        migrations.AlterUniqueTogether(
            name='turnevent',
            unique_together={('campaign', 'turn_index')},
        ),
    ]
