# Generated by Django 5.2.8 on 2025-11-23 01:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universes', '0001_homebrew_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoreChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_type', models.CharField(choices=[('hard_canon', 'Hard Canon'), ('soft_lore', 'Soft Lore')], max_length=20)),
                ('source_ref', models.CharField(help_text='doc id or turn id', max_length=100)),
                ('text', models.TextField()),
                ('tags_json', models.JSONField(default=list)),
                ('time_range_json', models.JSONField(default=dict, help_text='start_year, end_year, in_universe_date')),
                ('is_compacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supersedes_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='lore.lorechunk')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lore_chunks', to='universes.universe')),
            ],
            options={
                'verbose_name': 'Lore Chunk',
                'verbose_name_plural': 'Lore Chunks',
            },
        ),
    ]
