# Generated by Django 5.2.8 on 2025-11-23 01:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("srd", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Universe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "tone_profile_json",
                    models.JSONField(
                        default=dict,
                        help_text="Sliders: grimdark/cozy, comedy/serious, low/high magic, etc.",
                    ),
                ),
                (
                    "rules_profile_json",
                    models.JSONField(
                        default=dict, help_text="SRD baseline + homebrew overrides"
                    ),
                ),
                (
                    "calendar_profile_json",
                    models.JSONField(
                        default=dict, help_text="SRD-ish calendar configuration"
                    ),
                ),
                (
                    "current_universe_time",
                    models.JSONField(
                        default=dict, help_text="Current in-universe datetime"
                    ),
                ),
                ("canonical_lore_version", models.PositiveIntegerField(default=0)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="universes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Universe",
                "verbose_name_plural": "Universes",
            },
        ),
        migrations.CreateModel(
            name="HomebrewClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("srd_derived", "SRD Derived"),
                            ("homebrew", "Homebrew"),
                        ],
                        default="homebrew",
                        help_text="Whether this is derived from SRD or purely homebrew",
                        max_length=20,
                    ),
                ),
                (
                    "power_tier",
                    models.CharField(
                        choices=[
                            ("weak", "Weak"),
                            ("standard", "Standard"),
                            ("strong", "Strong"),
                            ("very_strong", "Very Strong"),
                            ("legendary", "Legendary"),
                        ],
                        default="standard",
                        help_text="Relative power level of this content",
                        max_length=20,
                    ),
                ),
                (
                    "suggested_level_min",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum suggested character level for this content",
                    ),
                ),
                (
                    "suggested_level_max",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Maximum suggested character level for this content",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked after universe creation is complete",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hit_die",
                    models.PositiveIntegerField(
                        help_text="Hit die size (e.g., 8 for d8)"
                    ),
                ),
                (
                    "primary_ability",
                    models.JSONField(
                        default=list,
                        help_text="Primary ability scores, e.g., ['str'] or ['str', 'dex']",
                    ),
                ),
                (
                    "saving_throw_proficiencies",
                    models.JSONField(
                        default=list,
                        help_text="Saving throw proficiency ability abbreviations",
                    ),
                ),
                (
                    "armor_proficiencies",
                    models.JSONField(
                        default=list, help_text="List of armor proficiencies"
                    ),
                ),
                (
                    "weapon_proficiencies",
                    models.JSONField(
                        default=list, help_text="List of weapon proficiencies"
                    ),
                ),
                (
                    "tool_proficiencies",
                    models.JSONField(
                        default=list, help_text="List of tool proficiency options"
                    ),
                ),
                (
                    "skill_choices",
                    models.JSONField(
                        default=dict,
                        help_text="Skill selection options, e.g., {'count': 2, 'from': ['Acrobatics', 'Athletics']}",
                    ),
                ),
                (
                    "starting_equipment",
                    models.JSONField(
                        default=list, help_text="Starting equipment options"
                    ),
                ),
                (
                    "spellcasting_ability",
                    models.CharField(
                        blank=True,
                        help_text="Spellcasting ability abbreviation (str, dex, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "features",
                    models.JSONField(default=list, help_text="Class features by level"),
                ),
                (
                    "subclass_level",
                    models.PositiveIntegerField(
                        default=3, help_text="Level at which subclass is chosen"
                    ),
                ),
                (
                    "spell_slots",
                    models.JSONField(
                        default=dict,
                        help_text="Spell slots by level, e.g., {'1': {'1': 2, '2': 3}, ...}",
                    ),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="universes.universe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homebrew Class",
                "verbose_name_plural": "Homebrew Classes",
                "ordering": ["universe", "name"],
            },
        ),
        migrations.CreateModel(
            name="HomebrewBackground",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("srd_derived", "SRD Derived"),
                            ("homebrew", "Homebrew"),
                        ],
                        default="homebrew",
                        help_text="Whether this is derived from SRD or purely homebrew",
                        max_length=20,
                    ),
                ),
                (
                    "power_tier",
                    models.CharField(
                        choices=[
                            ("weak", "Weak"),
                            ("standard", "Standard"),
                            ("strong", "Strong"),
                            ("very_strong", "Very Strong"),
                            ("legendary", "Legendary"),
                        ],
                        default="standard",
                        help_text="Relative power level of this content",
                        max_length=20,
                    ),
                ),
                (
                    "suggested_level_min",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum suggested character level for this content",
                    ),
                ),
                (
                    "suggested_level_max",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Maximum suggested character level for this content",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked after universe creation is complete",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skill_proficiencies",
                    models.JSONField(
                        default=list, help_text="List of skill proficiency names"
                    ),
                ),
                (
                    "tool_proficiencies",
                    models.JSONField(
                        default=list, help_text="List of tool proficiencies granted"
                    ),
                ),
                (
                    "languages",
                    models.JSONField(default=list, help_text="Language options"),
                ),
                (
                    "equipment",
                    models.JSONField(default=list, help_text="Starting equipment"),
                ),
                ("feature_name", models.CharField(blank=True, max_length=100)),
                ("feature_description", models.TextField(blank=True)),
                (
                    "suggested_characteristics",
                    models.JSONField(
                        default=dict,
                        help_text="Personality traits, ideals, bonds, flaws tables",
                    ),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="universes.universe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homebrew Background",
                "verbose_name_plural": "Homebrew Backgrounds",
                "ordering": ["universe", "name"],
            },
        ),
        migrations.CreateModel(
            name="UniverseHardCanonDoc",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("upload", "User Upload"),
                            ("worldgen", "World Generation"),
                            ("user_edit", "User Edit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("raw_text", models.TextField()),
                ("checksum", models.CharField(max_length=64)),
                ("never_compact", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hard_canon_docs",
                        to="universes.universe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hard Canon Document",
                "verbose_name_plural": "Hard Canon Documents",
            },
        ),
        migrations.CreateModel(
            name="HomebrewSubclass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("srd_derived", "SRD Derived"),
                            ("homebrew", "Homebrew"),
                        ],
                        default="homebrew",
                        help_text="Whether this is derived from SRD or purely homebrew",
                        max_length=20,
                    ),
                ),
                (
                    "power_tier",
                    models.CharField(
                        choices=[
                            ("weak", "Weak"),
                            ("standard", "Standard"),
                            ("strong", "Strong"),
                            ("very_strong", "Very Strong"),
                            ("legendary", "Legendary"),
                        ],
                        default="standard",
                        help_text="Relative power level of this content",
                        max_length=20,
                    ),
                ),
                (
                    "suggested_level_min",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum suggested character level for this content",
                    ),
                ),
                (
                    "suggested_level_max",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Maximum suggested character level for this content",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked after universe creation is complete",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "srd_parent_class_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of SRD parent class (if extending SRD class)",
                        max_length=100,
                    ),
                ),
                (
                    "subclass_level",
                    models.PositiveIntegerField(
                        default=3, help_text="Level at which this subclass is chosen"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list, help_text="Subclass features by level"
                    ),
                ),
                (
                    "parent_class",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to homebrew parent class (if homebrew)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subclasses",
                        to="universes.homebrewclass",
                    ),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="universes.universe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homebrew Subclass",
                "verbose_name_plural": "Homebrew Subclasses",
                "ordering": ["universe", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("universe", "name"),
                        name="unique_homebrew_subclass_per_universe",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HomebrewSpell",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("srd_derived", "SRD Derived"),
                            ("homebrew", "Homebrew"),
                        ],
                        default="homebrew",
                        help_text="Whether this is derived from SRD or purely homebrew",
                        max_length=20,
                    ),
                ),
                (
                    "power_tier",
                    models.CharField(
                        choices=[
                            ("weak", "Weak"),
                            ("standard", "Standard"),
                            ("strong", "Strong"),
                            ("very_strong", "Very Strong"),
                            ("legendary", "Legendary"),
                        ],
                        default="standard",
                        help_text="Relative power level of this content",
                        max_length=20,
                    ),
                ),
                (
                    "suggested_level_min",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum suggested character level for this content",
                    ),
                ),
                (
                    "suggested_level_max",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Maximum suggested character level for this content",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked after universe creation is complete",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.PositiveIntegerField(
                        help_text="Spell level (0 for cantrips)"
                    ),
                ),
                ("casting_time", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                (
                    "components",
                    models.JSONField(
                        default=dict,
                        help_text="Components dict, e.g., {'verbal': true, 'somatic': true, 'material': 'a bit of fur'}",
                    ),
                ),
                ("duration", models.CharField(max_length=100)),
                ("concentration", models.BooleanField(default=False)),
                ("ritual", models.BooleanField(default=False)),
                (
                    "higher_levels",
                    models.TextField(
                        blank=True, help_text="At Higher Levels description"
                    ),
                ),
                (
                    "dice_expression",
                    models.CharField(
                        blank=True,
                        help_text="Damage/healing dice, e.g., '8d6'",
                        max_length=50,
                    ),
                ),
                (
                    "class_restrictions",
                    models.JSONField(
                        default=list,
                        help_text="List of class names that can use this spell (empty = all)",
                    ),
                ),
                (
                    "damage_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homebrew_spells",
                        to="srd.damagetype",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="homebrew_spells",
                        to="srd.spellschool",
                    ),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="universes.universe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homebrew Spell",
                "verbose_name_plural": "Homebrew Spells",
                "ordering": ["universe", "level", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("universe", "name"),
                        name="unique_homebrew_spell_per_universe",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HomebrewSpecies",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("srd_derived", "SRD Derived"),
                            ("homebrew", "Homebrew"),
                        ],
                        default="homebrew",
                        help_text="Whether this is derived from SRD or purely homebrew",
                        max_length=20,
                    ),
                ),
                (
                    "power_tier",
                    models.CharField(
                        choices=[
                            ("weak", "Weak"),
                            ("standard", "Standard"),
                            ("strong", "Strong"),
                            ("very_strong", "Very Strong"),
                            ("legendary", "Legendary"),
                        ],
                        default="standard",
                        help_text="Relative power level of this content",
                        max_length=20,
                    ),
                ),
                (
                    "suggested_level_min",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum suggested character level for this content",
                    ),
                ),
                (
                    "suggested_level_max",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Maximum suggested character level for this content",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked after universe creation is complete",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("tiny", "Tiny"),
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "speed",
                    models.PositiveIntegerField(
                        default=30, help_text="Base walking speed in feet"
                    ),
                ),
                (
                    "ability_bonuses",
                    models.JSONField(
                        default=dict,
                        help_text="Ability score bonuses, e.g., {'str': 2, 'con': 1}",
                    ),
                ),
                (
                    "traits",
                    models.JSONField(
                        default=list, help_text="List of racial trait objects"
                    ),
                ),
                (
                    "languages",
                    models.JSONField(default=list, help_text="List of languages known"),
                ),
                (
                    "darkvision",
                    models.PositiveIntegerField(
                        default=0, help_text="Darkvision range in feet (0 if none)"
                    ),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="universes.universe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homebrew Species",
                "verbose_name_plural": "Homebrew Species",
                "ordering": ["universe", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("universe", "name"),
                        name="unique_homebrew_species_per_universe",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HomebrewMonster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("srd_derived", "SRD Derived"),
                            ("homebrew", "Homebrew"),
                        ],
                        default="homebrew",
                        help_text="Whether this is derived from SRD or purely homebrew",
                        max_length=20,
                    ),
                ),
                (
                    "power_tier",
                    models.CharField(
                        choices=[
                            ("weak", "Weak"),
                            ("standard", "Standard"),
                            ("strong", "Strong"),
                            ("very_strong", "Very Strong"),
                            ("legendary", "Legendary"),
                        ],
                        default="standard",
                        help_text="Relative power level of this content",
                        max_length=20,
                    ),
                ),
                (
                    "suggested_level_min",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum suggested character level for this content",
                    ),
                ),
                (
                    "suggested_level_max",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Maximum suggested character level for this content",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked after universe creation is complete",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("tiny", "Tiny"),
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("huge", "Huge"),
                            ("gargantuan", "Gargantuan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("alignment", models.CharField(blank=True, max_length=50)),
                ("armor_class", models.PositiveIntegerField()),
                (
                    "armor_description",
                    models.CharField(
                        blank=True,
                        help_text="Source of AC (natural armor, etc.)",
                        max_length=100,
                    ),
                ),
                ("hit_points", models.PositiveIntegerField()),
                (
                    "hit_dice",
                    models.CharField(
                        help_text="Hit dice expression, e.g., '4d8+4'", max_length=20
                    ),
                ),
                (
                    "speed",
                    models.JSONField(
                        default=dict,
                        help_text="Speed types and values, e.g., {'walk': 30, 'fly': 60}",
                    ),
                ),
                (
                    "ability_scores",
                    models.JSONField(
                        default=dict,
                        help_text="Ability scores dict, e.g., {'str': 16, 'dex': 12, ...}",
                    ),
                ),
                (
                    "saving_throws",
                    models.JSONField(default=dict, help_text="Saving throw bonuses"),
                ),
                ("skills", models.JSONField(default=dict, help_text="Skill bonuses")),
                (
                    "senses",
                    models.JSONField(
                        default=dict, help_text="Senses and passive perception"
                    ),
                ),
                (
                    "languages",
                    models.JSONField(default=list, help_text="Languages known"),
                ),
                (
                    "challenge_rating",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Challenge rating (0.125 for 1/8, etc.)",
                        max_digits=5,
                    ),
                ),
                ("experience_points", models.PositiveIntegerField()),
                ("traits", models.JSONField(default=list, help_text="Special traits")),
                (
                    "actions",
                    models.JSONField(default=list, help_text="Actions available"),
                ),
                (
                    "reactions",
                    models.JSONField(default=list, help_text="Reactions available"),
                ),
                (
                    "legendary_actions",
                    models.JSONField(
                        default=list, help_text="Legendary actions if any"
                    ),
                ),
                (
                    "lair_actions",
                    models.JSONField(default=list, help_text="Lair actions if any"),
                ),
                (
                    "regional_effects",
                    models.JSONField(default=list, help_text="Regional effects if any"),
                ),
                (
                    "condition_immunities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="immune_homebrew_monsters",
                        to="srd.condition",
                    ),
                ),
                (
                    "damage_immunities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="immune_homebrew_monsters",
                        to="srd.damagetype",
                    ),
                ),
                (
                    "damage_resistances",
                    models.ManyToManyField(
                        blank=True,
                        related_name="resistant_homebrew_monsters",
                        to="srd.damagetype",
                    ),
                ),
                (
                    "damage_vulnerabilities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vulnerable_homebrew_monsters",
                        to="srd.damagetype",
                    ),
                ),
                (
                    "monster_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="homebrew_monsters",
                        to="srd.monstertype",
                    ),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="universes.universe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homebrew Monster",
                "verbose_name_plural": "Homebrew Monsters",
                "ordering": ["universe", "challenge_rating", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("universe", "name"),
                        name="unique_homebrew_monster_per_universe",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HomebrewItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("srd_derived", "SRD Derived"),
                            ("homebrew", "Homebrew"),
                        ],
                        default="homebrew",
                        help_text="Whether this is derived from SRD or purely homebrew",
                        max_length=20,
                    ),
                ),
                (
                    "power_tier",
                    models.CharField(
                        choices=[
                            ("weak", "Weak"),
                            ("standard", "Standard"),
                            ("strong", "Strong"),
                            ("very_strong", "Very Strong"),
                            ("legendary", "Legendary"),
                        ],
                        default="standard",
                        help_text="Relative power level of this content",
                        max_length=20,
                    ),
                ),
                (
                    "suggested_level_min",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum suggested character level for this content",
                    ),
                ),
                (
                    "suggested_level_max",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Maximum suggested character level for this content",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked after universe creation is complete",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cost_gp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost in gold pieces",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "weight_lb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in pounds",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("very_rare", "Very Rare"),
                            ("legendary", "Legendary"),
                            ("artifact", "Artifact"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("magical", models.BooleanField(default=False)),
                ("requires_attunement", models.BooleanField(default=False)),
                (
                    "attunement_requirements",
                    models.CharField(
                        blank=True,
                        help_text="Attunement requirements if any",
                        max_length=200,
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        default=dict, help_text="Item-specific properties"
                    ),
                ),
                ("is_weapon", models.BooleanField(default=False)),
                (
                    "weapon_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("simple_melee", "Simple Melee"),
                            ("simple_ranged", "Simple Ranged"),
                            ("martial_melee", "Martial Melee"),
                            ("martial_ranged", "Martial Ranged"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "damage_dice",
                    models.CharField(
                        blank=True, help_text="Damage dice, e.g., '1d8'", max_length=20
                    ),
                ),
                (
                    "weapon_properties",
                    models.JSONField(
                        default=list,
                        help_text="Weapon properties (finesse, versatile, etc.)",
                    ),
                ),
                (
                    "range_normal",
                    models.PositiveIntegerField(
                        blank=True, help_text="Normal range in feet", null=True
                    ),
                ),
                (
                    "range_long",
                    models.PositiveIntegerField(
                        blank=True, help_text="Long range in feet", null=True
                    ),
                ),
                ("is_armor", models.BooleanField(default=False)),
                (
                    "armor_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("light", "Light"),
                            ("medium", "Medium"),
                            ("heavy", "Heavy"),
                            ("shield", "Shield"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "base_ac",
                    models.PositiveIntegerField(
                        blank=True, help_text="Base armor class", null=True
                    ),
                ),
                (
                    "dex_bonus",
                    models.CharField(
                        default="full",
                        help_text="DEX bonus: 'full', 'max2', or 'none'",
                        max_length=20,
                    ),
                ),
                (
                    "strength_requirement",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum STR to avoid speed penalty",
                        null=True,
                    ),
                ),
                ("stealth_disadvantage", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="homebrew_items",
                        to="srd.itemcategory",
                    ),
                ),
                (
                    "damage_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homebrew_items",
                        to="srd.damagetype",
                    ),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="universes.universe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homebrew Item",
                "verbose_name_plural": "Homebrew Items",
                "ordering": ["universe", "category", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("universe", "name"),
                        name="unique_homebrew_item_per_universe",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HomebrewFeat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("srd_derived", "SRD Derived"),
                            ("homebrew", "Homebrew"),
                        ],
                        default="homebrew",
                        help_text="Whether this is derived from SRD or purely homebrew",
                        max_length=20,
                    ),
                ),
                (
                    "power_tier",
                    models.CharField(
                        choices=[
                            ("weak", "Weak"),
                            ("standard", "Standard"),
                            ("strong", "Strong"),
                            ("very_strong", "Very Strong"),
                            ("legendary", "Legendary"),
                        ],
                        default="standard",
                        help_text="Relative power level of this content",
                        max_length=20,
                    ),
                ),
                (
                    "suggested_level_min",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum suggested character level for this content",
                    ),
                ),
                (
                    "suggested_level_max",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Maximum suggested character level for this content",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked after universe creation is complete",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prerequisites",
                    models.JSONField(
                        default=dict,
                        help_text="Prerequisites for taking this feat, e.g., {'level': 4, 'ability': {'str': 13}}",
                    ),
                ),
                (
                    "benefits",
                    models.JSONField(
                        default=list, help_text="List of benefits granted by this feat"
                    ),
                ),
                (
                    "ability_score_increase",
                    models.JSONField(
                        default=dict,
                        help_text="Ability score increases, e.g., {'choice': ['str', 'dex'], 'amount': 1}",
                    ),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="universes.universe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homebrew Feat",
                "verbose_name_plural": "Homebrew Feats",
                "ordering": ["universe", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("universe", "name"),
                        name="unique_homebrew_feat_per_universe",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="homebrewclass",
            constraint=models.UniqueConstraint(
                fields=("universe", "name"), name="unique_homebrew_class_per_universe"
            ),
        ),
        migrations.AddConstraint(
            model_name="homebrewbackground",
            constraint=models.UniqueConstraint(
                fields=("universe", "name"),
                name="unique_homebrew_background_per_universe",
            ),
        ),
    ]
