# Generated by Django 5.2.8 on 2025-11-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universes', '0001_homebrew_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universehardcanondoc',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hard Canon Document', 'verbose_name_plural': 'Hard Canon Documents'},
        ),
    ]
