# Generated by Django 5.2.8 on 2025-11-24 00:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universes', '0002_alter_universehardcanondoc_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldgenSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='draft', max_length=20)),
                ('mode', models.CharField(choices=[('ai_collab', 'AI Collaboration'), ('manual', 'Manual')], default='ai_collab', max_length=20)),
                ('draft_data_json', models.JSONField(default=dict, help_text='Draft universe data: name, description, tone, rules, calendar, lore, homebrew')),
                ('step_status_json', models.JSONField(default=dict, help_text='Completion status per step: {step_name: {complete: bool, fields: {...}}}')),
                ('conversation_json', models.JSONField(default=list, help_text="Array of {role: 'user'|'assistant', content: str, timestamp: str}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resulting_universe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worldgen_session', to='universes.universe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldgen_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worldgen Session',
                'verbose_name_plural': 'Worldgen Sessions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
