# Generated by Django 5.2.8 on 2025-12-01 03:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universes', '0003_add_worldgen_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoreSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('current_document_json', models.JSONField(default=dict, help_text='Current document draft: {title: str, content: str, tags: list[str]}')),
                ('conversation_json', models.JSONField(default=list, help_text="Array of {role: 'user'|'assistant', content: str, timestamp: str}")),
                ('draft_documents_json', models.JSONField(default=list, help_text='Array of draft documents: [{title, content, tags}, ...]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lore_sessions', to='universes.universe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lore_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lore Session',
                'verbose_name_plural': 'Lore Sessions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
