# Generated by Django 5.2.8 on 2025-11-23 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbilityScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbreviation", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Ability Score",
                "verbose_name_plural": "Ability Scores",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                (
                    "effects",
                    models.JSONField(
                        default=list,
                        help_text="List of mechanical effects this condition applies",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DamageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Damage Type",
                "verbose_name_plural": "Damage Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Feat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "prerequisites",
                    models.JSONField(
                        default=dict, help_text="Prerequisites for taking this feat"
                    ),
                ),
                (
                    "benefits",
                    models.JSONField(
                        default=list, help_text="List of benefits granted by this feat"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "cost_gp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost in gold pieces",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "weight_lb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in pounds",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("very_rare", "Very Rare"),
                            ("legendary", "Legendary"),
                            ("artifact", "Artifact"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("magical", models.BooleanField(default=False)),
                ("requires_attunement", models.BooleanField(default=False)),
                (
                    "attunement_requirements",
                    models.CharField(
                        blank=True,
                        help_text="Attunement requirements if any",
                        max_length=200,
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        default=dict, help_text="Item-specific properties"
                    ),
                ),
            ],
            options={
                "ordering": ["category__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Item Category",
                "verbose_name_plural": "Item Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MonsterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Monster Type",
                "verbose_name_plural": "Monster Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("tiny", "Tiny"),
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "speed",
                    models.PositiveIntegerField(
                        default=30, help_text="Base walking speed in feet"
                    ),
                ),
                (
                    "ability_bonuses",
                    models.JSONField(
                        default=dict,
                        help_text="Ability score bonuses, e.g., {'str': 2, 'con': 1}",
                    ),
                ),
                (
                    "traits",
                    models.JSONField(
                        default=list, help_text="List of racial trait objects"
                    ),
                ),
                (
                    "languages",
                    models.JSONField(default=list, help_text="List of languages known"),
                ),
                (
                    "darkvision",
                    models.PositiveIntegerField(
                        default=0, help_text="Darkvision range in feet (0 if none)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Species",
                "verbose_name_plural": "Species",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SpellSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Spell School",
                "verbose_name_plural": "Spell Schools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "hit_die",
                    models.PositiveIntegerField(
                        help_text="Hit die size (e.g., 8 for d8)"
                    ),
                ),
                (
                    "armor_proficiencies",
                    models.JSONField(
                        default=list, help_text="List of armor proficiencies"
                    ),
                ),
                (
                    "weapon_proficiencies",
                    models.JSONField(
                        default=list, help_text="List of weapon proficiencies"
                    ),
                ),
                (
                    "tool_proficiencies",
                    models.JSONField(
                        default=list, help_text="List of tool proficiency options"
                    ),
                ),
                (
                    "skill_choices",
                    models.JSONField(
                        default=dict,
                        help_text="Skill selection options, e.g., {'count': 2, 'from': ['Acrobatics', 'Athletics']}",
                    ),
                ),
                (
                    "starting_equipment",
                    models.JSONField(
                        default=list, help_text="Starting equipment options"
                    ),
                ),
                (
                    "features",
                    models.JSONField(default=list, help_text="Class features by level"),
                ),
                (
                    "primary_ability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_for_classes",
                        to="srd.abilityscore",
                    ),
                ),
                (
                    "saving_throw_proficiencies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="saving_throw_classes",
                        to="srd.abilityscore",
                    ),
                ),
                (
                    "spellcasting_ability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spellcasting_classes",
                        to="srd.abilityscore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Class",
                "verbose_name_plural": "Character Classes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Armor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "armor_type",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("medium", "Medium"),
                            ("heavy", "Heavy"),
                            ("shield", "Shield"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_ac", models.PositiveIntegerField(help_text="Base armor class")),
                (
                    "dex_bonus",
                    models.CharField(
                        default="full",
                        help_text="DEX bonus: 'full', 'max2', or 'none'",
                        max_length=20,
                    ),
                ),
                (
                    "strength_requirement",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum STR to avoid speed penalty",
                        null=True,
                    ),
                ),
                ("stealth_disadvantage", models.BooleanField(default=False)),
                (
                    "don_time",
                    models.CharField(
                        blank=True, help_text="Time to don armor", max_length=50
                    ),
                ),
                (
                    "doff_time",
                    models.CharField(
                        blank=True, help_text="Time to doff armor", max_length=50
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="armor_stats",
                        to="srd.item",
                    ),
                ),
            ],
            options={
                "ordering": ["armor_type", "item__name"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="srd.itemcategory",
            ),
        ),
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("tiny", "Tiny"),
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("huge", "Huge"),
                            ("gargantuan", "Gargantuan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("alignment", models.CharField(blank=True, max_length=50)),
                ("armor_class", models.PositiveIntegerField()),
                (
                    "armor_description",
                    models.CharField(
                        blank=True,
                        help_text="Source of AC (natural armor, etc.)",
                        max_length=100,
                    ),
                ),
                ("hit_points", models.PositiveIntegerField()),
                (
                    "hit_dice",
                    models.CharField(
                        help_text="Hit dice expression, e.g., '4d8+4'", max_length=20
                    ),
                ),
                (
                    "speed",
                    models.JSONField(
                        default=dict,
                        help_text="Speed types and values, e.g., {'walk': 30, 'fly': 60}",
                    ),
                ),
                (
                    "ability_scores",
                    models.JSONField(default=dict, help_text="Ability scores dict"),
                ),
                (
                    "saving_throws",
                    models.JSONField(default=dict, help_text="Saving throw bonuses"),
                ),
                ("skills", models.JSONField(default=dict, help_text="Skill bonuses")),
                (
                    "senses",
                    models.JSONField(
                        default=dict, help_text="Senses and passive perception"
                    ),
                ),
                (
                    "languages",
                    models.JSONField(default=list, help_text="Languages known"),
                ),
                (
                    "challenge_rating",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Challenge rating (0.125 for 1/8, etc.)",
                        max_digits=5,
                    ),
                ),
                ("experience_points", models.PositiveIntegerField()),
                ("traits", models.JSONField(default=list, help_text="Special traits")),
                (
                    "actions",
                    models.JSONField(default=list, help_text="Actions available"),
                ),
                (
                    "reactions",
                    models.JSONField(default=list, help_text="Reactions available"),
                ),
                (
                    "legendary_actions",
                    models.JSONField(
                        default=list, help_text="Legendary actions if any"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "condition_immunities",
                    models.ManyToManyField(
                        blank=True, related_name="immune_monsters", to="srd.condition"
                    ),
                ),
                (
                    "damage_immunities",
                    models.ManyToManyField(
                        blank=True, related_name="immune_monsters", to="srd.damagetype"
                    ),
                ),
                (
                    "damage_resistances",
                    models.ManyToManyField(
                        blank=True,
                        related_name="resistant_monsters",
                        to="srd.damagetype",
                    ),
                ),
                (
                    "damage_vulnerabilities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vulnerable_monsters",
                        to="srd.damagetype",
                    ),
                ),
                (
                    "monster_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monsters",
                        to="srd.monstertype",
                    ),
                ),
            ],
            options={
                "ordering": ["challenge_rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "ability_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="skills",
                        to="srd.abilityscore",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Background",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "tool_proficiencies",
                    models.JSONField(
                        default=list, help_text="List of tool proficiencies granted"
                    ),
                ),
                (
                    "languages",
                    models.JSONField(default=list, help_text="Language options"),
                ),
                (
                    "equipment",
                    models.JSONField(default=list, help_text="Starting equipment"),
                ),
                ("feature_name", models.CharField(blank=True, max_length=100)),
                ("feature_description", models.TextField(blank=True)),
                (
                    "suggested_characteristics",
                    models.JSONField(
                        default=dict,
                        help_text="Personality traits, ideals, bonds, flaws tables",
                    ),
                ),
                (
                    "skill_proficiencies",
                    models.ManyToManyField(
                        blank=True, related_name="backgrounds", to="srd.skill"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "level",
                    models.PositiveIntegerField(
                        help_text="Spell level (0 for cantrips)"
                    ),
                ),
                ("casting_time", models.CharField(max_length=100)),
                ("range", models.CharField(max_length=100)),
                (
                    "components",
                    models.JSONField(
                        default=dict,
                        help_text="Components dict, e.g., {'verbal': true, 'somatic': true, 'material': 'a bit of fur'}",
                    ),
                ),
                ("duration", models.CharField(max_length=100)),
                ("concentration", models.BooleanField(default=False)),
                ("ritual", models.BooleanField(default=False)),
                ("description", models.TextField()),
                (
                    "higher_levels",
                    models.TextField(
                        blank=True, help_text="At Higher Levels description"
                    ),
                ),
                (
                    "dice_expression",
                    models.CharField(
                        blank=True,
                        help_text="Damage/healing dice, e.g., '8d6'",
                        max_length=50,
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True, related_name="spells", to="srd.characterclass"
                    ),
                ),
                (
                    "damage_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spells",
                        to="srd.damagetype",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spells",
                        to="srd.spellschool",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weapon_type",
                    models.CharField(
                        choices=[
                            ("simple_melee", "Simple Melee"),
                            ("simple_ranged", "Simple Ranged"),
                            ("martial_melee", "Martial Melee"),
                            ("martial_ranged", "Martial Ranged"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "damage_dice",
                    models.CharField(
                        help_text="Damage dice, e.g., '1d8'", max_length=20
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        default=list,
                        help_text="Weapon properties (finesse, versatile, etc.)",
                    ),
                ),
                (
                    "range_normal",
                    models.PositiveIntegerField(
                        blank=True, help_text="Normal range in feet", null=True
                    ),
                ),
                (
                    "range_long",
                    models.PositiveIntegerField(
                        blank=True, help_text="Long range in feet", null=True
                    ),
                ),
                (
                    "versatile_dice",
                    models.CharField(
                        blank=True,
                        help_text="Two-handed damage dice if versatile",
                        max_length=20,
                    ),
                ),
                (
                    "damage_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weapons",
                        to="srd.damagetype",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weapon_stats",
                        to="srd.item",
                    ),
                ),
            ],
            options={
                "ordering": ["weapon_type", "item__name"],
            },
        ),
        migrations.CreateModel(
            name="Subclass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "subclass_level",
                    models.PositiveIntegerField(
                        default=3, help_text="Level at which this subclass is chosen"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list, help_text="Subclass features by level"
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subclasses",
                        to="srd.characterclass",
                    ),
                ),
            ],
            options={
                "ordering": ["character_class__name", "name"],
                "unique_together": {("name", "character_class")},
            },
        ),
    ]
