# Generated by Django 5.2.8 on 2025-11-23 02:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("universes", "0001_homebrew_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterSheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "species",
                    models.CharField(
                        help_text="Species name (from SRD or homebrew)", max_length=100
                    ),
                ),
                (
                    "character_class",
                    models.CharField(help_text="Primary class name", max_length=100),
                ),
                (
                    "subclass",
                    models.CharField(
                        blank=True,
                        help_text="Subclass name (if chosen)",
                        max_length=100,
                    ),
                ),
                (
                    "background",
                    models.CharField(help_text="Character background", max_length=100),
                ),
                (
                    "alignment",
                    models.CharField(
                        blank=True,
                        help_text="Character alignment (e.g., 'Lawful Good')",
                        max_length=50,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("tiny", "Tiny"),
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        default="medium",
                        help_text="Character size from species",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "experience_points",
                    models.PositiveIntegerField(default=0, help_text="Total XP earned"),
                ),
                (
                    "multiclass_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Multiclass levels, e.g., {'Fighter': 3, 'Wizard': 2}",
                    ),
                ),
                (
                    "hit_points_max",
                    models.PositiveIntegerField(default=0, help_text="Maximum HP"),
                ),
                (
                    "hit_points_current",
                    models.PositiveIntegerField(default=0, help_text="Current HP"),
                ),
                (
                    "hit_points_temp",
                    models.PositiveIntegerField(default=0, help_text="Temporary HP"),
                ),
                (
                    "hit_dice_json",
                    models.JSONField(
                        default=dict,
                        help_text="Hit dice by type with max/spent tracking",
                    ),
                ),
                (
                    "ability_scores_json",
                    models.JSONField(
                        default=dict,
                        help_text="Ability scores: str, dex, con, int, wis, cha",
                    ),
                ),
                (
                    "skills_json",
                    models.JSONField(
                        default=dict, help_text="Skill proficiencies and expertise"
                    ),
                ),
                (
                    "proficiencies_json",
                    models.JSONField(
                        default=dict,
                        help_text="Armor, weapon, tool, language, and saving throw proficiencies",
                    ),
                ),
                (
                    "speed",
                    models.PositiveIntegerField(
                        default=30, help_text="Base walking speed in feet"
                    ),
                ),
                (
                    "speed_modifiers_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional speeds: fly, swim, climb, burrow",
                    ),
                ),
                (
                    "armor_class",
                    models.PositiveIntegerField(
                        default=10, help_text="Current AC including armor and modifiers"
                    ),
                ),
                (
                    "armor_class_base",
                    models.PositiveIntegerField(
                        default=10, help_text="Base AC without equipment"
                    ),
                ),
                (
                    "initiative_bonus",
                    models.IntegerField(
                        default=0, help_text="Total initiative modifier"
                    ),
                ),
                (
                    "features_json",
                    models.JSONField(
                        default=list,
                        help_text="Class, species, and background features",
                    ),
                ),
                (
                    "spellbook_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Spellcasting info, known spells, prepared spells, spell slots",
                    ),
                ),
                (
                    "equipment_json",
                    models.JSONField(
                        default=dict,
                        help_text="Inventory, equipped items, money, encumbrance",
                    ),
                ),
                (
                    "personality_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Personality traits, ideals, bonds, flaws",
                    ),
                ),
                (
                    "homebrew_overrides_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="References to homebrew content (species, class, items, etc.)",
                    ),
                ),
                (
                    "conditions_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Active conditions (blinded, charmed, etc.)",
                    ),
                ),
                (
                    "death_saves_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Death save successes and failures: {'successes': 0, 'failures': 0}",
                    ),
                ),
                (
                    "backstory",
                    models.TextField(
                        blank=True, help_text="Character backstory and history"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Player notes about the character"
                    ),
                ),
                (
                    "appearance",
                    models.TextField(
                        blank=True, help_text="Physical appearance description"
                    ),
                ),
                (
                    "has_inspiration",
                    models.BooleanField(
                        default=False,
                        help_text="Whether character currently has inspiration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "universe",
                    models.ForeignKey(
                        blank=True,
                        help_text="Universe this character belongs to (for homebrew content)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="characters",
                        to="universes.universe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Sheet",
                "verbose_name_plural": "Character Sheets",
                "ordering": ["-updated_at"],
            },
        ),
    ]
