# Generated by Django 5.2.8 on 2025-11-23 01:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universes', '0001_homebrew_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('character_class', models.CharField(max_length=50)),
                ('subclass', models.CharField(blank=True, max_length=50)),
                ('background', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField(default=1)),
                ('ability_scores_json', models.JSONField(default=dict)),
                ('skills_json', models.JSONField(default=dict)),
                ('proficiencies_json', models.JSONField(default=dict)),
                ('features_json', models.JSONField(default=dict)),
                ('spellbook_json', models.JSONField(default=dict)),
                ('equipment_json', models.JSONField(default=dict)),
                ('homebrew_overrides_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('universe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='universes.universe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Character Sheet',
                'verbose_name_plural': 'Character Sheets',
            },
        ),
    ]
