# Generated by Django 5.2.8 on 2025-11-23 00:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmEndpointConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(choices=[('openai', 'OpenAI'), ('azure-openai', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('local', 'Local/Custom')], max_length=50)),
                ('base_url', models.URLField(blank=True)),
                ('api_key_encrypted', models.BinaryField(help_text='AES-GCM encrypted API key')),
                ('default_model', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Endpoint Config',
                'verbose_name_plural': 'LLM Endpoint Configs',
            },
        ),
    ]
