# Generated by Django 5.2.8 on 2025-11-23 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmendpointconfig',
            options={'ordering': ['-created_at'], 'verbose_name': 'LLM Endpoint Config', 'verbose_name_plural': 'LLM Endpoint Configs'},
        ),
    ]
